key_words_1 = ["AI", "artificial", "artificial intelligence", "chatbot", "bot", "GPT", "chatGPT", "language model",
               "digital", "griefbot", "thanabot"]
key_words_2 = ["loss", "grief", "bereavement", "mourning","condolences", "heartfelt",
               "sorrow", "comfort", "healing", "support", "coping", "trauma", "emotional", "pain", "devastated",
               "griefbot", "thanabot","Replika","StoryFile","Uare.ai","Eternos","character.AI"]
key_words_3 = [
    "GPT-3",
    "GPT-4",
    "GPT-4o",
    "Claude",
    "ChatGPT",
    "Mistral",
    "OpenAI",
    "gpt3",
    "gpt4",
    "gpt4o",
    "agent",
    "bot",
    "software",
    "services",
    "A.I.",
    "A.I",
    "digital replica",
    "simulation",
    "Replika",
    "StoryFile",
    "Uare.ai",
    "Eternos",
    "character.AI",
    "large language model",
    "neural network",
    "machine learning",
    "deep learning",
    "transformer",
    "fine-tuning",
    "prompt engineering",
]

webapp = "https://www.reddit.com/prefs/apps"